# Implementing Backpropagation using Pytorch

In [1]:
import torch

In [2]:
'''requires_grad: This member, if true starts tracking all the operation history and forms a backward graph
for gradient calculation  and If requires_grad is set to false, you are freezing the part of the model as no changes 
happen to its parameters.'''
#reuqires_grad = True ------> indicates that yes we have to do the backpropagation using the torch input 
x = torch.tensor(4.0,requires_grad = True)

In [3]:
x

tensor(4., requires_grad=True)

In [4]:
y = x**2

In [5]:
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
#Implementing backpropagation

In [7]:
#backward function mainly helps in backpropagation , y = 2x
y.backward()

In [8]:
print(x.grad)

tensor(8.)


In [9]:
lst = [[1.,2.,3.],[2.,3.,4.],[1.,3.,5.]]
torch_input = torch.tensor(lst,requires_grad = True)

In [10]:
torch_input

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [1., 3., 5.]], requires_grad=True)

In [11]:
# equation  => y = x**3 + x**2 (after one backpropagation we will compute the derivative)
# => 3x**2 + 2x
y = torch_input**3 + torch_input**2


In [12]:
y

tensor([[  2.,  12.,  36.],
        [ 12.,  36.,  80.],
        [  2.,  36., 150.]], grad_fn=<AddBackward0>)

In [13]:
z = y.sum()

In [14]:
z

tensor(366., grad_fn=<SumBackward0>)

In [15]:
z.backward()

In [16]:
print(torch_input.grad)

tensor([[ 5., 16., 33.],
        [16., 33., 56.],
        [ 5., 33., 85.]])
