# PYTORCH CODE TUTORIAL

In [1]:
'''
A Tensor is a generalization of vectors and matrices and is easily understood as a multi-dimensional array
It is a term and set of techniques in machine learning in the training and operation of deep learning models 
can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use 
the power of GPUs
Tensors are a type of data structure used in linear algebra and like vectors and matrices we can 
calculate arithmetic operations with tensors .'''

'\nA Tensor is a generalization of vectors and matrices and is easily understood as a multi-dimensional array\nIt is a term and set of techniques in machine learning in the training and operation of deep learning models \ncan be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use \nthe power of GPUs\nTensors are a type of data structure used in linear algebra and like vectors and matrices we can \ncalculate arithmetic operations with tensors .'

In [2]:
pip install torch 

Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch

In [4]:
torch.__version__ 

'1.12.1'

In [5]:
import numpy as np

In [6]:
#list , changing into numpy array
lst = [1,2,3,4]
arr = np.array(lst)

In [7]:
arr

array([1, 2, 3, 4])

# Converting numpy array to pytorch tensors

In [8]:
tensors = torch.from_numpy(arr)


In [9]:
tensors

tensor([1, 2, 3, 4])

In [10]:
#indexing
tensors[:2]

tensor([1, 2])

In [11]:
tensors[3] = 100


In [12]:
tensors

tensor([  1,   2,   3, 100])

In [13]:
arr

array([  1,   2,   3, 100])

In [14]:
#Disadvantages of from_numpy is that it uses the same memory location 


In [15]:
#This can be prevented by using torch.tensors

In [16]:
tensor_arr = torch.tensor(arr)

In [17]:
tensor_arr[3] = 120

In [18]:
tensor_arr

tensor([  1,   2,   3, 120])

In [19]:
arr

array([  1,   2,   3, 100])

In [20]:
#zeors and ones 
torch.ones(2,3,dtype = torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [21]:
torch.zeros(3,2,dtype = torch.float64)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [22]:
#matrices 
a = torch.tensor(np.arange(0,15).reshape(5,3))

In [23]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [24]:
#indexing 

In [25]:
a[:,0]

tensor([ 0,  3,  6,  9, 12])

In [26]:
a[:,-1]

tensor([ 2,  5,  8, 11, 14])

In [27]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])

# ARITHMETIC OPERATIONS

In [28]:
X = torch.tensor([1,2,3],dtype = torch.float)
Y = torch.tensor([3,2,1],dtype = torch.float)


In [29]:
print("The addition is :",X+Y)

The addition is : tensor([4., 4., 4.])


In [30]:
torch.add(X,Y)

tensor([4., 4., 4.])

In [31]:
#storing the output to another variable 
Z = torch.zeros(3)

In [32]:
torch.add(X,Y,out = Z)

tensor([4., 4., 4.])

In [33]:
Z

tensor([4., 4., 4.])

In [34]:
A = torch.tensor([2,5,9],dtype = torch.int)
B = torch.tensor([3,2,2],dtype = torch.int)


In [35]:
torch.add(A,B)

tensor([ 5,  7, 11], dtype=torch.int32)

In [36]:
torch.add(A,B).sum()

tensor(23)

# Dot product and Matrix Multiplication

In [37]:
A = torch.tensor([2,5,9],dtype = torch.int)
B = torch.tensor([3,2,2],dtype = torch.int)

In [38]:
A.mul(B)

tensor([ 6, 10, 18], dtype=torch.int32)

In [39]:
A.dot(B)

tensor(34, dtype=torch.int32)

In [40]:
#Matrix Multiplication

In [41]:
x = torch.tensor([[2,5,9],[1,2,3]],dtype = torch.int)
y = torch.tensor([[3,2,2],[1,2,3],[4,5,6]],dtype = torch.int)


In [42]:
torch.matmul(x,y)

tensor([[47, 59, 73],
        [17, 21, 26]], dtype=torch.int32)

In [43]:
torch.mm(x,y)

tensor([[47, 59, 73],
        [17, 21, 26]], dtype=torch.int32)

In [44]:
x@y

tensor([[47, 59, 73],
        [17, 21, 26]], dtype=torch.int32)