<a href="https://colab.research.google.com/github/soumo99/Deep-Learning-Code-Files/blob/main/Tensorflow_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Understanding of Tensorflow Concepts by code implementation

In [1]:
import tensorflow as tf

x = tf.constant([[1,2,3],[3,4,5]])

print(x)

tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [2]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [3]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [4]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.02398264 -1.6260436  -2.0670435 ]
 [-1.5892156  -2.6601038   1.7058688 ]
 [-1.717576   -1.155117    1.5146042 ]], shape=(3, 3), dtype=float32)


In [5]:
x = tf.random.uniform((3,3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.12678325 0.2388643  0.35444713]
 [0.9030018  0.579406   0.2933643 ]
 [0.50939095 0.02450025 0.54015887]], shape=(3, 3), dtype=float32)


In [6]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [7]:
x = tf.range(start=1,limit=10)
print(x)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [8]:
x = tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


Changing the data type from int ot float

In [9]:
x = tf.cast(x,dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


## Mathematical Operations

In [10]:
x = tf.constant([1,2,3])
y = tf.constant([1,2,3])

add = tf.add(x,y)
subtract = tf.subtract(x,y)
multiply = tf.multiply(x,y)
divide = tf.divide(x,y)
print(add)
print(subtract)
print(multiply)
print(divide)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)
tf.Tensor([1 4 9], shape=(3,), dtype=int32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float64)


Element wise multiplication

In [11]:
x = tf.constant([1,2,3])
y = tf.constant([1,2,3])

#tensordot and reduce_sum both are used for element wise multiplication
z = tf.tensordot(x,y,axes=1)
z = tf.reduce_sum(x*y,axis=0)
print(z)

tf.Tensor(14, shape=(), dtype=int32)


In [12]:
x = tf.constant([1,2,3])
y = tf.constant([1,2,3])

z = x ** 5

print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


Matrix Multiplication


In [13]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

print(x)
print(y)

z = tf.matmul(x,y)
print(z)

z = x @ y
print(z)

tf.Tensor(
[[-0.26209128 -1.4391097   0.9892394 ]
 [ 1.4304843   0.59072495 -0.40563685]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.46564585 -0.9263972   0.26792663 -1.8411181 ]
 [-0.9541549   0.07121553  0.97173953 -0.5781628 ]
 [-2.4732547   0.5491741   1.5747226   0.56474376]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-1.1955491   0.6835783   0.08911669  1.8732474 ]
 [ 1.1056992  -1.505893    0.31853008 -3.2043066 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-1.1955491   0.6835783   0.08911669  1.8732474 ]
 [ 1.1056992  -1.505893    0.31853008 -3.2043066 ]], shape=(2, 4), dtype=float32)


# Indexing Operation

In [14]:
x = tf.constant([1,2,3,4,5,6])
print(x)
print(x[:])

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [15]:
#Excluding the first element
print(x[1:])

#Defining a range of value from the list
print(x[1:3])

#Printing the elements on alternate 2 position
print(x[::2])

#Printing the elements in the reverse order
print(x[::-1])

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)
tf.Tensor([6 5 4 3 2 1], shape=(6,), dtype=int32)


# Indices

In [16]:
indices = tf.constant([1,3]) #Here [1,3] is the psoition of the list
x_ind = tf.gather(x,indices)
print(x_ind)

tf.Tensor([2 4], shape=(2,), dtype=int32)


In [17]:
x = tf.constant([[1,2],
                [3,4],
                [4,5]])

print(x[:])
print(x[::])
print(x[:2])
print(x[1:3])
#printing only the first element from the matrix
print(x[0,:])

tf.Tensor(
[[1 2]
 [3 4]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 4]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


# Reshaping

In [18]:
x = tf.range(9)
print(x)

y = tf.reshape(x,(3,3))
print(y)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


Transposing Matrix

In [19]:
# x = tf.transpose(x,perm=[1,0]) #perm stands for permutation
# print(x)